# Generated by Django 4.1 on 2022-09-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(default='Anonymoys', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(default='My tutorials')),
            ],
        ),
    ]
